Feature/backend response request
swsnu/swpp2020-team8 pull request #76
Opened 2020-11-23 14:43 UTC by GooJinSun

## What does this PR do?

- ResponseRequest model, view, serializer, API testing
- testing
![image](https://user-images.githubusercontent.com/37523788/99975309-6b8b8b00-2de5-11eb-8970-729cedd60d74.png)
- pylint
![image](https://user-images.githubusercontent.com/37523788/99975354-76462000-2de5-11eb-82a3-6afda2ebe277.png)

+ Design and Planning과 조금 다르게 구현되었습니다!
관련 업데이트 사항은 Design and Planning에 업데이트 해두겠습니다~

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code Style Update (formatting, renaming)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

## Further comments
백 + 장고 CBV랑 DRF가 생각보다 익숙치 않아서 구현이 늦어졌습니다ㅠㅠ
다음엔 자신 없거나 안해본 건 최대한 일찍 시작해보도록 하겠습니다!
도와준 + 도와줄 @ssm0318 에게 심심찮은 감사와 사과를 전합니다......❤️

2020-11-23 17:24 UTC, ssm0318 commented on backend/adoorback/adoorback/utils/seed.py
> +      ResponseRequest.objects.create(actor=actor, recipient=recipient, question=question)
알 수도 있지만 혹시라도 모를까봐 말하자면 만약 여기 unique constraint가 있었으면
create 대신 get_or_create 쓰면 해결됐을거야!

2020-11-23 17:26 UTC, ssm0318 commented on backend/adoorback/feed/serializers.py
> +class ResponseRequestSerializer(serializers.ModelSerializer):
구웃~

2020-11-23 17:27 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        self.assertEqual(ResponseRequest.objects.all().filter(actor_id=user.id).count(), 0)
recipient기준으로도 확인해주세요 count가 0인지!

2020-11-23 17:28 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        self.assertEqual(ResponseRequest.objects.all().filter(recipient_id=user.id).count(), 0)
actor 기준으로도 없는지 확인해주세요~

2020-11-23 17:28 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        self.assertEqual(ResponseRequest.objects.all().filter(recipient_id=user.id).count(), 0)
@koyrkr 왜 본인의 경우와 달리 이 경우는 둘을 각기 따로 검사하는지 이해되셨길~ (friendship은 쌍방향이지만 response request는 일방향이니까)

2020-11-23 17:29 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +    def test_on_delete_question_cascade(self):
꼼꼼테스트 굿~~~

2020-11-23 17:29 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        current_user = self.make_user(username='current_user')
철저히 변수명들로만 범벅한 코드 베리굿~

2020-11-23 17:30 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +            self.assertEqual(response.data['count'], 1)
굿 테스팅!!
@koyrkr 아까 friendship list 테스트 다시 해달라고 한거 확인 못한채로 머지가 되었던데 이런 테스팅을 말한 것이었습니다~

2020-11-23 17:31 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        response = self.client.post('/api/user/login/', json.dumps(login_data), content_type='application/json')
보다시피 여기도 fbv에서 client 사용해서 보냈음~

2020-11-23 17:31 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        response = self.client.post('/api/user/login/', json.dumps(login_data), content_type='application/json')
(슬랙으로 얘기한 내용 관련)

2020-11-23 17:34 UTC, ssm0318 commented on backend/adoorback/feed/tests.py
> +        # GET - not allowed request
구웃~

2020-11-23 17:35 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +    #TODO: 친구에게만 질문 보내기 가능
풀해서 구현해주세요~

2020-11-23 17:36 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +    def get_queryset(self):
굿!!

2020-11-23 17:36 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +        new_response_request = ResponseRequest(actor=request.user, recipient=recipient, question=question)
.create() method를 안 쓰는 특별한 이유가 있나요?

2020-11-23 17:39 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +    elif request.method == 'DELETE':
굿~

2020-11-23 17:42 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +    elif request.method == 'PATCH':
+ responded는 serializer에서 렌더할 필드이지 db에 들어갈 필드는 아닌 것 같습니다.
comment serializer의 is_reply 같은 필드 가져오는 방식을 확인해보세요~

2020-11-23 17:43 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +@api_view(["POST", "PATCH", "DELETE"])
굿

2020-11-23 17:43 UTC, ssm0318 requested changes
고생했습니다! 좀 더 수정해주세요~

2020-11-23 18:59 UTC, GooJinSun commented on backend/adoorback/adoorback/utils/seed.py
> +      ResponseRequest.objects.create(actor=actor, recipient=recipient, question=question)
오 완전 몰랐어

2020-11-23 18:59 UTC, GooJinSun commented on backend/adoorback/adoorback/utils/seed.py
> +      ResponseRequest.objects.create(actor=actor, recipient=recipient, question=question)
@ssm0318 생각해보니 actor랑 recipient랑 같으면 안될거 같은데 이런건 어떻게 처리해주면 좋을까?

2020-11-23 19:18 UTC, GooJinSun commented on backend/adoorback/feed/tests.py
> +        self.assertEqual(ResponseRequest.objects.all().filter(actor_id=user.id).count(), 0)
오 생각지도 못햇던 부분이네요
꼼꼼하게 봐주셔서 감사합니당!!

2020-11-23 19:18 UTC, GooJinSun commented on backend/adoorback/feed/views.py
> +        new_response_request = ResponseRequest(actor=request.user, recipient=recipient, question=question)
생성된 response request를 serializer에 넣어주려고 이렇게 짯는데
`.create()`로 구현하면 어떤 점이 더 좋은가요?

2020-11-23 19:18 UTC, GooJinSun commented on backend/adoorback/feed/views.py
> +    elif request.method == 'PATCH':
> response를 create하는 method에서 post_create를 할 때 patch를 장고 백에서 직접 해주는 로직이 되어야할 것 같습니다
구현하면서 헷갈렸던 부분인데 좋은 지적인 것 같습니당!
1. responded 필드는 db에서 제외시키고, response 를 ForeignKey로 추가시키고
2. reponded는 response가 비어있지 않은 경우를 가지고와서 serializer에서 렌더시킨다(`responded`)
3. response를 create할 때 해당되는 response request를 찾아서 있다면 response를 넣어준다..?
이렇게 하면 어떨까요? @ssm0318 


> responded가 다시 false가 되는 경우는 언제인가요?

이런 경우는 없습니다...!

2020-11-23 19:35 UTC, ssm0318 commented on backend/adoorback/adoorback/utils/seed.py
> +      ResponseRequest.objects.create(actor=actor, recipient=recipient, question=question)
@GooJinSun (습관적 질문을 자제하자 ^_^) view나 모델에서도 해줄 수 있지만 프론트에서 잘 처리하는게 제일 좋은 것 같아

2020-11-23 19:36 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +        new_response_request = ResponseRequest(actor=request.user, recipient=recipient, question=question)
@GooJinSun 넣어준다는게 무슨 말이지? 두 줄로 쓸 필요 없이 한 줄로 해결되니까?

2020-11-23 19:36 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +        new_response_request = ResponseRequest(actor=request.user, recipient=recipient, question=question)
여기서는 특별히 validation 해주고 잇는 것 같지 않은데 아닌가?

2020-11-23 19:39 UTC, ssm0318 commented on backend/adoorback/feed/views.py
> +    elif request.method == 'PATCH':
1. foreign key로 추가해야만 하는 이유가 없는듯
2. foreign key로 추가하면 비어있을 수가 없는데 처음에 request가 만들어질 때 비어있음
3. 위에서 설명한 이유로 다르게 해야함 (response request를 걍 없애면 될듯)

2020-11-23 22:38 UTC, koyrkr reviewed
저도 아직 백린이이지만, 꼼꼼하게 짜고 꼼꼼하게 테스팅하셨다는 게 아주 잘 보였어요 👍 수고하셨습니다!

2020-11-23 22:38 UTC, koyrkr commented on backend/adoorback/feed/models.py
> +        return self.question.content
오오 FriendRequest (아직 구현중) 의 모델이랑 거의 비슷하겠네요 생각해보니! 잘 짜주신 ResponseRequest보고 참고할 것은 잘 참고하도록 하겠습니다 👍

2020-11-23 22:38 UTC, koyrkr commented on backend/adoorback/feed/tests.py
> +class ResponseRequestTestCase(TestCase):
꼼꼼하게 테스트 굳! 저도 앞으로 모델 테스팅할때 더 꼼꼼하게 해봐야겠어용

2020-11-23 22:39 UTC, koyrkr approved these changes

2020-11-24 07:42 UTC, GooJinSun commented on backend/adoorback/feed/views.py
> +    elif request.method == 'PATCH':
맞네맞네 비어잇을수가 없네요
오키 그럼 patch관련 api, responded field를 없애보겠습니다!

2020-11-24 15:15 UTC, ssm0318 approved these changes
고생 많으셨습니다!!!!!!!!!!

2020-11-25 06:21 UTC, merged